### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by klugben** [yexleo/OpenAI_wechat_bot#1]
楼主您好,

我按照指南进行安装,显示报错:
![图片](https://klugben66.oss-cn-hongkong.aliyuncs.com/AICODING01/Screenshot%20314.jpg)

**Comment by yexleo** [comment]
注意我的介绍里写的是windows系统.你报错这个库,是wxauto这个库要求的,而且是win的, 目前没在mac下跑过.但是理论上wxauto库是支持mac的,麻烦去研究一下那个库.

**Comment by yexleo** [comment]
注意这个项目是windows系统下的.我刚才又看了一眼wxauto库,确实只支持pc版,mac目前是不行的.
